name: CI

on:
  push:
    branches:
      - "feature/**"
      - "bugfix/**"
      - "hotfix/**"
      - "main"
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Extract Project Metadata
        id: meta
        run: |
          CHILD_PATH=":app"
          PROP_OUTPUT=$(./gradlew -q ${CHILD_PATH}:properties --no-daemon)
          GROUP=$(echo "$PROP_OUTPUT" | grep "^group:" | awk '{print $2}')
          VERSION=$(echo "$PROP_OUTPUT" | grep "^version:" | awk '{print $2}')
          ARTIFACT_ID=$(echo "$PROP_OUTPUT" | grep "^name:" | awk '{print $2}')
          GROUP_PATH=$(echo $GROUP | tr '.' '/')
          echo "Group=$GROUP, Version=$VERSION, Artifact=$ARTIFACT_ID, Path=$GROUP_PATH"

          echo "GROUP_PATH=$GROUP_PATH" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "ARTIFACT_ID=$ARTIFACT_ID" >> $GITHUB_ENV

      - name: Check Artifact in GitHub Packages
        id: check_pkg
        run: |
          URL="https://maven.pkg.github.com/${{ github.repository }}/${{ env.GROUP_PATH }}/${{ env.ARTIFACT_ID }}/${{ env.VERSION }}/${{ env.ARTIFACT_ID }}-${{ env.VERSION }}.jar"
          echo "Checking URL: $URL"

          STATUS=$(curl -s -L -o /dev/null -w "%{http_code}" -u "${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}" $URL)

          if [ "$STATUS" -eq 200 ]; then
            echo "::notice ::Package Version ${{ env.VERSION }} already exists. Cancelling CI."
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Cancel if exists
        if: steps.check_pkg.outputs.exists == 'true'
        run: |
          gh run cancel ${{ github.run_id }}
        env:
          GITHUB_H_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Unit Test
        run: ./gradlew test

      - name: Functionality Test
        run: ./gradlew functionTest

      # PR시점, 스모크테스트를 진행한다
      - name: Smoke Test
        if: github.event_name == 'pull_request'
        run: ./gradlew smokeTest

      # PR시점, 중요 회귀테스트를 진행한다
      - name: Critical Regression Test
        if: github.event_name == 'pull_request'
        run: ./gradlew regressionTest -DexcludeTags="slow,skip"

      # MERGE시, 전체 회귀테스트를 진행한다
      - name: Full Regression Test
        if: github.ref == 'refs/heads/main'
        run: ./gradlew regressionTest

      # MERGE시, 배포할 jar 파일을 빌드한다
      - name: Build Application
        if: github.ref == 'refs/heads/main'
        run: ./gradlew assemble

      # MERGE시, 스테이징에 반영한다
      - name: Upload to Staging
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          retention-days: 1
          path: |
            app/build/libs/*.jar
